// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCY66Wn9j-Kz-KAUoVvCddvXDJbnv616c',
    appId: '1:1028268986947:web:6190b3a7759f49b4097af6',
    messagingSenderId: '1028268986947',
    projectId: 'menu-app-b5c23',
    authDomain: 'menu-app-b5c23.firebaseapp.com',
    storageBucket: 'menu-app-b5c23.firebasestorage.app',
    measurementId: 'G-PLHR3NW9YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD1AG_ZrFs6NXieEENfzz36cpPqJlZkFA',
    appId: '1:1028268986947:android:eab1bccb5042d062097af6',
    messagingSenderId: '1028268986947',
    projectId: 'menu-app-b5c23',
    storageBucket: 'menu-app-b5c23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1qTCU_XHQYI9HS9ooo-jjIjjQseDtoBw',
    appId: '1:1028268986947:ios:f4a0ea9faeb3e50d097af6',
    messagingSenderId: '1028268986947',
    projectId: 'menu-app-b5c23',
    storageBucket: 'menu-app-b5c23.firebasestorage.app',
    iosBundleId: 'com.example.menuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1qTCU_XHQYI9HS9ooo-jjIjjQseDtoBw',
    appId: '1:1028268986947:ios:f4a0ea9faeb3e50d097af6',
    messagingSenderId: '1028268986947',
    projectId: 'menu-app-b5c23',
    storageBucket: 'menu-app-b5c23.firebasestorage.app',
    iosBundleId: 'com.example.menuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCY66Wn9j-Kz-KAUoVvCddvXDJbnv616c',
    appId: '1:1028268986947:web:e533c6e6fa95ab0b097af6',
    messagingSenderId: '1028268986947',
    projectId: 'menu-app-b5c23',
    authDomain: 'menu-app-b5c23.firebaseapp.com',
    storageBucket: 'menu-app-b5c23.firebasestorage.app',
    measurementId: 'G-KX9M5WZJ5H',
  );
}
